FROM python:3.7-buster

# 必要なものをインストール
RUN apt-get update && \
    apt-get -y install nginx

COPY requirements.txt /var/app/

# flask、uwsgiをインストール
RUN pip install -r /var/app/requirements.txt

# アプリケーションをコピー
COPY . /var/app

# Nginxの設定ファイルをコピー
COPY default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

# 起動
CMD ["/bin/bash", "/var/app/startup.sh"]
